
# This file was *autogenerated* from the file script_llegir_punt.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16)
with open("raw/certificate_subjectPublicKey.bin", "rb") as f:
	certificate = f.read()


Px = int(certificate[_sage_const_1 :((len(certificate) - _sage_const_1 )//_sage_const_2  + _sage_const_1 )].encode('hex'),_sage_const_16 )
Py = int(certificate[((len(certificate) - _sage_const_1 )//_sage_const_2  + _sage_const_1 ):_sage_const_2 *(((len(certificate) - _sage_const_1 )//_sage_const_2 )+_sage_const_1 )].encode('hex'),_sage_const_16 )
print(Px)
print(Py)

