
# This file was *autogenerated* from the file ../../Universitat/7/c/lab2_casa/program.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256); _sage_const_250 = Integer(250); _sage_const_249 = Integer(249)
k = GF(_sage_const_256 , names=('a',)); (a,) = k._first_ngens(1)
print(k)
q = GF(_sage_const_256 , names=('b',)); (b,) = q._first_ngens(1)
a = _sage_const_250 
b = _sage_const_249 
print(a*b)

